# Generated by Django 4.2.14 on 2024-12-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Sender', models.IntegerField()),
                ('Recepient', models.IntegerField(default=-1)),
                ('message', models.CharField(max_length=255, null=True)),
                ('ReadBy', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('TeacherId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=14, unique=True)),
                ('Email', models.EmailField(max_length=254, null=True, unique=True)),
                ('Course', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('JoinDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
