# Generated by Django 4.2.14 on 2024-12-05 21:19

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_coursecontent_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='visibleToAll',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='file',
            field=models.FileField(upload_to=pathlib.PurePosixPath('/media/sf_john_kli/help/new/lms/media/course_contents')),
        ),
    ]
