# Generated by Django 5.1.3 on 2024-12-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_websignup_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
    ]
