# Generated by Django 5.1.3 on 2025-02-05 13:22

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='file',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/Admin/Desktop/web/lms/media/course_contents')),
        ),
    ]
